const SUCCESS_STATUS_CODE = 200;
const NOT_FOUND_STATUS_CODE = 400;
const ERROR_META_API_STATUS_CODE = 202;
const ERROR_CATCH_STATUS_CODE = 203;

module.exports = {
    SUCCESS_STATUS_CODE,
    NOT_FOUND_STATUS_CODE,
    ERROR_META_API_STATUS_CODE,
    ERROR_CATCH_STATUS_CODE,
};